{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-chart-2.serviceAccountName" . }}
  namespace: {{ include "test-chart-2.namespace" . }}
  labels:
    {{- include "test-chart-2.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.serviceAccount.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
