name: Notifications

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      # - name: Load YAML configuration
      #   id: read
      #   uses: step-security/action-read-yaml@705ee0c6475c5a26a356e79ee380eb3527b3772d
      #   with:
      #     config: ${{ github.workspace }}/examples/basic.yaml

      - name: Send custom event details to a Slack workflow
        uses: slackapi/slack-github-action@v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            status: "${{ job.status }}"
            name: "${{ github.event.release.name }}"
            release: "${{ github.event.release.tag_name }}"
            user: "${{ github.actor }}"
            user_url: "${{ github.event.release.author.html_url }}"
            repository: "https://github.com/${{ github.repository }}"
            tag_link: "${{ github.event.release.html_url }}"
            published_at: "${{ github.event.release.published_at }}"
